### ISSUE TITLE
Kubernetes Core bundle does not start on localhost

### ISSUE THREAD

**Issue by joedborg** [juju-solutions/bundle-canonical-kubernetes#247]
Using Juju 2.1.2, `0/lxd/0` won't come up:
```
Model    Controller  Cloud/Region         Version
default  lxd         localhost/localhost  2.1.2

App                Version  Status       Scale  Charm              Store       Rev  OS      Notes
easyrsa                     waiting        0/1  easyrsa            jujucharms    7  ubuntu
etcd               2.2.5    blocked          1  etcd               jujucharms   24  ubuntu
flannel            0.7.0    blocked          2  flannel            jujucharms   11  ubuntu
kubernetes-master  1.5.3    maintenance      1  kubernetes-master  jujucharms   12  ubuntu  exposed
kubernetes-worker  1.5.3    waiting          1  kubernetes-worker  jujucharms   14  ubuntu  exposed

Unit                  Workload     Agent       Machine  Public address  Ports  Message
easyrsa/0             waiting      allocating  0/lxd/0                         waiting for machine
etcd/0*               blocked      idle        0        10.175.236.161         Missing relation to certificate authority.
kubernetes-master/0*  maintenance  idle        0        10.175.236.161         Rendering authentication templates.
  flannel/0*          blocked      idle                 10.175.236.161         Waiting for etcd relation.
kubernetes-worker/0*  waiting      idle        1        10.175.236.2           Waiting for kubelet to start.
  flannel/1           blocked      idle                 10.175.236.2           Waiting for etcd relation.

Machine  State    DNS             Inst id        Series  AZ
0        started  10.175.236.161  juju-917855-0  xenial
0/lxd/0  down                     pending        xenial
1        started  10.175.236.2    juju-917855-1  xenial

Relation      Provides           Consumes           Type
certificates  easyrsa            etcd               regular
certificates  easyrsa            kubernetes-master  regular
certificates  easyrsa            kubernetes-worker  regular
cluster       etcd               etcd               peer
etcd          etcd               flannel            regular
etcd          etcd               kubernetes-master  regular
cni           flannel            kubernetes-master  regular
cni           flannel            kubernetes-worker  regular
cni           kubernetes-master  flannel            subordinate
kube-dns      kubernetes-master  kubernetes-worker  regular
cni           kubernetes-worker  flannel            subordinate
```

And output from `lxc list`
```
+---------------+---------+--------------------------------+------+------------+-----------+
|     NAME      |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+---------------+---------+--------------------------------+------+------------+-----------+
| juju-44d73a-0 | RUNNING | 10.175.236.218 (eth0)          |      | PERSISTENT | 0         |
|               |         | 10.0.3.1 (lxdbr0)              |      |            |           |
+---------------+---------+--------------------------------+------+------------+-----------+
| juju-44d73a-1 | RUNNING | 172.17.0.1 (docker0)           |      | PERSISTENT | 0         |
|               |         | 10.175.236.246 (eth0)          |      |            |           |
+---------------+---------+--------------------------------+------+------------+-----------+
| juju-894d8f-0 | RUNNING | 10.175.236.146 (eth0)          |      | PERSISTENT | 0         |
+---------------+---------+--------------------------------+------+------------+-----------+
```

**Comment by marcoceppi** [comment]
How did launch this cluster? Can you also `juju status --format yaml easyrsa` for additional output?

**Comment by joedborg** [comment]
Hey Marco,

Launch wise, just
```
juju bootstrap localhost lxd
juju deploy kubernetes-core
```
And the output of `status`
```
model:
  name: default
  controller: lxd
  cloud: localhost
  region: localhost
  version: 2.2-beta2
  model-status:
    current: available
    since: 04 Apr 2017 15:06:01+01:00
machines:
  "0":
    juju-status:
      current: started
      since: 04 Apr 2017 15:07:35+01:00
      version: 2.2-beta2
    dns-name: 10.175.236.14
    ip-addresses:
    - 10.175.236.14
    instance-id: juju-19d03f-0
    machine-status:
      current: running
      message: Running
      since: 04 Apr 2017 15:07:01+01:00
    series: xenial
    network-interfaces:
      eth0:
        ip-addresses:
        - 10.175.236.14
        mac-address: 00:16:3e:6a:8f:c4
        is-up: true
      lxdbr0:
        ip-addresses:
        - 10.0.7.1
        mac-address: 5e:ea:ac:dd:2b:a8
        is-up: true
    containers:
      0/lxd/0:
        juju-status:
          current: down
          message: agent is not communicating with the server
          since: 04 Apr 2017 15:11:49+01:00
        instance-id: pending
        machine-status:
          current: provisioning error
          message: 'Failed to change ownership of: /var/lib/lxd/containers/juju-19d03f-0-lxd-0/rootfs'
          since: 04 Apr 2017 15:11:49+01:00
        series: xenial
    hardware: arch=amd64 cores=0 mem=0M
applications:
  easyrsa:
    charm: cs:~containers/easyrsa-7
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: easyrsa
    charm-rev: 7
    exposed: false
    application-status:
      current: waiting
      message: waiting for machine
      since: 04 Apr 2017 15:06:47+01:00
    relations:
      client:
      - etcd
      - kubernetes-master
      - kubernetes-worker
    units:
      easyrsa/0:
        workload-status:
          current: waiting
          message: waiting for machine
          since: 04 Apr 2017 15:06:47+01:00
        juju-status:
          current: allocating
          since: 04 Apr 2017 15:06:47+01:00
        machine: 0/lxd/0
```

**Comment by joedborg** [comment]
I guess 
```'Failed to change ownership of: /var/lib/lxd/containers/juju-19d03f-0-lxd-0/rootfs'```
is the key error here, so could well be an issue on my box, rather than the bundle.  AWS deployment works fine.

**Comment by chuckbutler** [comment]
Right, LXD deployments dont work ootb with K8s-core. We instead recommend the use of conjure-up.

Try instaling conjure-up and giving that a go

```
snap install conjure-up
conjure-up kubernetes-core
```

This should tweak and tune the lxd profiles and the bundle appropriately to accomodate a lxd deployment.

**Comment by joedborg** [comment]
Hey Chuck!

Yeah, I tried that as well.  C-U bootstraps the the LXD juju controller fine, but doesn't seem to launch any of the LXD containers for the rest of the machines; just sits in "waiting for machine"

And `juju status`:

```Machine  State  DNS  Inst id  Series  AZ  Message
0        down        pending  xenial      not found
1        down        pending  xenial      not found
2        down        pending  xenial      not found
3        down        pending  xenial      not found
```

**Comment by marcoceppi** [comment]
So, that's interesting, and problematic. Could you do the following:

```
juju status --format yaml
```

Could you also do:
```
lxc profile show juju-$(juju switch | awk -F/ '{print $2}')
```

Finally,

```
lxc launch ubuntu:x -p  juju-$(juju switch | awk -F/ '{print $2}')
```

The output of each of these as well as:

```
conjure-up --version
lxc version
```

**Comment by joedborg** [comment]
Hey Marco, 

I have the issue on both my desktop and laptop - my desktop has Juju and LXD from PPAs and my laptop from snap packages.  Both have conjure up from snaps.  I'll paste from my desktop for now (can do the same from laptop if you think there'd be any difference).

`juju status --format yaml`
```
model:
  name: conjure-up-kubernetes-core-0b1
  controller: conjure-up-localhost-5ee
  cloud: localhost
  region: localhost
  version: 2.1.2
machines:
  "0":
    juju-status:
      current: down
      message: agent is not communicating with the server
      since: 06 Apr 2017 09:36:58+01:00
    instance-id: pending
    machine-status:
      current: provisioning error
      message: not found
      since: 06 Apr 2017 09:36:58+01:00
    series: xenial
  "1":
    juju-status:
      current: down
      message: agent is not communicating with the server
      since: 06 Apr 2017 09:37:31+01:00
    instance-id: pending
    machine-status:
      current: provisioning error
      message: not found
      since: 06 Apr 2017 09:37:31+01:00
    series: xenial
  "2":
    juju-status:
      current: down
      message: agent is not communicating with the server
      since: 06 Apr 2017 09:38:05+01:00
    instance-id: pending
    machine-status:
      current: provisioning error
      message: not found
      since: 06 Apr 2017 09:38:05+01:00
    series: xenial
  "3":
    juju-status:
      current: down
      message: agent is not communicating with the server
      since: 06 Apr 2017 09:38:39+01:00
    instance-id: pending
    machine-status:
      current: provisioning error
      message: not found
      since: 06 Apr 2017 09:38:39+01:00
    series: xenial
applications:
  easyrsa:
    charm: cs:~containers/xenial/easyrsa-7
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: easyrsa
    charm-rev: 7
    exposed: false
    application-status:
      current: waiting
      message: waiting for machine
      since: 06 Apr 2017 09:36:22+01:00
    relations:
      client:
      - etcd
      - kubernetes-master
      - kubernetes-worker
    units:
      easyrsa/0:
        workload-status:
          current: waiting
          message: waiting for machine
          since: 06 Apr 2017 09:36:22+01:00
        juju-status:
          current: allocating
          since: 06 Apr 2017 09:36:22+01:00
        machine: "0"
  etcd:
    charm: cs:~containers/xenial/etcd-24
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: etcd
    charm-rev: 24
    exposed: false
    application-status:
      current: waiting
      message: waiting for machine
      since: 06 Apr 2017 09:36:26+01:00
    relations:
      certificates:
      - easyrsa
      cluster:
      - etcd
      db:
      - flannel
      - kubernetes-master
    units:
      etcd/0:
        workload-status:
          current: waiting
          message: waiting for machine
          since: 06 Apr 2017 09:36:26+01:00
        juju-status:
          current: allocating
          since: 06 Apr 2017 09:36:26+01:00
        machine: "1"
  flannel:
    charm: cs:~containers/xenial/flannel-11
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: flannel
    charm-rev: 11
    exposed: false
    application-status:
      current: waiting
      message: waiting for machine
      since: 06 Apr 2017 09:36:28+01:00
    relations:
      cni:
      - kubernetes-master
      - kubernetes-worker
      etcd:
      - etcd
    subordinate-to:
    - kubernetes-master
    - kubernetes-worker
  kubernetes-master:
    charm: cs:~containers/xenial/kubernetes-master-12
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: kubernetes-master
    charm-rev: 12
    exposed: true
    application-status:
      current: waiting
      message: waiting for machine
      since: 06 Apr 2017 09:36:31+01:00
    relations:
      certificates:
      - easyrsa
      cluster-dns:
      - kubernetes-worker
      cni:
      - flannel
      etcd:
      - etcd
      kube-api-endpoint:
      - kubernetes-worker
    units:
      kubernetes-master/0:
        workload-status:
          current: waiting
          message: waiting for machine
          since: 06 Apr 2017 09:36:31+01:00
        juju-status:
          current: allocating
          since: 06 Apr 2017 09:36:31+01:00
        machine: "2"
  kubernetes-worker:
    charm: cs:~containers/xenial/kubernetes-worker-14
    series: xenial
    os: ubuntu
    charm-origin: jujucharms
    charm-name: kubernetes-worker
    charm-rev: 14
    exposed: true
    application-status:
      current: waiting
      message: waiting for machine
      since: 06 Apr 2017 09:36:34+01:00
    relations:
      certificates:
      - easyrsa
      cni:
      - flannel
      kube-api-endpoint:
      - kubernetes-master
      kube-dns:
      - kubernetes-master
    units:
      kubernetes-worker/0:
        workload-status:
          current: waiting
          message: waiting for machine
          since: 06 Apr 2017 09:36:34+01:00
        juju-status:
          current: allocating
          since: 06 Apr 2017 09:36:34+01:00
        machine: "3"
```
`lxc profile show juju-$(juju switch | awk -F/ '{print $2}')`
```
config:
  boot.autostart: "true"
  linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
  raw.lxc: |
    lxc.aa_profile=unconfined
    lxc.mount.auto=proc:rw sys:rw
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  aadisable:
    path: /sys/module/nf_conntrack/parameters/hashsize
    source: /dev/null
    type: disk
  aadisable1:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
  root:
    path: /
    pool: default
    type: disk
name: juju-conjure-up-kubernetes-core-0b1
used_by: []
```
`lxc launch ubuntu:x -p  juju-$(juju switch | awk -F/ '{print $2}')`
```
Creating darling-barnacle
error: not found
```

`conjure-up 2.1.2`
`lxc 2.12`

Thanks!

**Comment by tvansteenburgh** [comment]
@joedborg Curious if you tried with the latest conjure-up (2.2.1)?

**Comment by joedborg** [comment]
Hey @tvansteenburgh,
If I try with 2.2.2 I get:

```
2017-06-29 11:45:47,615 [DEBUG] conjure-up/_unspecified_spell - app.py:258 - LXD version: 2.14, Juju version: 2.2.1-zesty-amd64, conjure-up version: 2.2.2
2017-06-29 11:45:47,651 [INFO] conjure-up/_unspecified_spell - events.py:178 - Watching for shutdown
2017-06-29 11:45:47,730 [DEBUG] conjure-up/_unspecified_spell - events.py:55 - Awaiting Shutdown at conjureup/events.py:180
2017-06-29 11:45:50,536 [DEBUG] conjure-up/canonical-kubernetes - download.py:60 - Path is local filesystem, copying /snap/conjure-up/527/spells/canonical-kubernetes to /home/joe/.cache/conjure-up/canonical-kubernetes
2017-06-29 11:45:50,549 [DEBUG] conjure-up/canonical-kubernetes - utils.py:392 - Pulling bundle for canonical-kubernetes from channel: stable
2017-06-29 11:45:58,176 [INFO] conjure-up/canonical-kubernetes - common.py:77 - Bootstrapping Juju controller.
2017-06-29 11:45:58,176 [DEBUG] conjure-up/canonical-kubernetes - juju.py:139 - Bootstrapping to set region: {}
2017-06-29 11:45:58,182 [DEBUG] conjure-up/canonical-kubernetes - juju.py:170 - bootstrap cmd: ['juju', 'bootstrap', 'joyent/eu-ams-1', 'conjure-up-joyent-554', '--default-model', 'conjure-canonical-kubern-be1', '--config', 'image-stream=daily', '--config', 'enable-os-upgrade=false', '--bootstrap-series', 'xenial', '--credential', 'myjoyent']
2017-06-29 11:45:58,205 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting ModelConnected at conjureup/controllers/deploy/common.py:23
2017-06-29 11:45:58,224 [DEBUG] conjure-up/canonical-kubernetes - juju.py:179 - waiting for proc
2017-06-29 11:46:03,737 [DEBUG] conjure-up/canonical-kubernetes - juju.py:181 - proc done
2017-06-29 11:46:03,738 [ERROR] conjure-up/canonical-kubernetes - common.py:36 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-joyent-554" on joyent/eu-ams-1', 'ERROR failed to bootstrap model: no image metadata found']
2017-06-29 11:46:03,740 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Setting Error at conjureup/events.py:147
2017-06-29 11:46:03,820 [ERROR] conjure-up/canonical-kubernetes - events.py:166 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/527/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 39, in do_bootstrap
    app.current_cloud_type))
Exception: Unable to bootstrap (cloud type: joyent)
2017-06-29 11:46:03,826 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:21 - Showing dialog for exception: Unable to bootstrap (cloud type: joyent)
2017-06-29 11:46:05,426 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Setting Shutdown at conjureup/events.py:143
2017-06-29 11:46:05,428 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Received Shutdown at conjureup/events.py:180
2017-06-29 11:46:05,429 [INFO] conjure-up/canonical-kubernetes - events.py:184 - Shutting down
2017-06-29 11:46:07,797 [DEBUG] conjure-up/_unspecified_spell - app.py:258 - LXD version: 2.14, Juju version: 2.2.1-zesty-amd64, conjure-up version: 2.2.2
2017-06-29 11:46:07,832 [INFO] conjure-up/_unspecified_spell - events.py:178 - Watching for shutdown
2017-06-29 11:46:07,912 [DEBUG] conjure-up/_unspecified_spell - events.py:55 - Awaiting Shutdown at conjureup/events.py:180
2017-06-29 11:46:13,814 [DEBUG] conjure-up/canonical-kubernetes - download.py:60 - Path is local filesystem, copying /snap/conjure-up/527/spells/canonical-kubernetes to /home/joe/.cache/conjure-up/canonical-kubernetes
2017-06-29 11:46:13,822 [DEBUG] conjure-up/canonical-kubernetes - utils.py:392 - Pulling bundle for canonical-kubernetes from channel: stable
2017-06-29 11:46:19,987 [INFO] conjure-up/canonical-kubernetes - common.py:77 - Bootstrapping Juju controller.
2017-06-29 11:46:19,988 [DEBUG] conjure-up/canonical-kubernetes - juju.py:139 - Bootstrapping to set region: {}
2017-06-29 11:46:19,994 [DEBUG] conjure-up/canonical-kubernetes - juju.py:170 - bootstrap cmd: ['juju', 'bootstrap', 'joyent/eu-ams-1', 'conjure-up-joyent-91a', '--default-model', 'conjure-canonical-kubern-6fc', '--config', 'image-stream=daily', '--config', 'enable-os-upgrade=false', '--bootstrap-series', 'xenial', '--credential', 'myjoyent']
2017-06-29 11:46:20,020 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting ModelConnected at conjureup/controllers/deploy/common.py:23
2017-06-29 11:46:20,039 [DEBUG] conjure-up/canonical-kubernetes - juju.py:179 - waiting for proc
2017-06-29 11:46:22,031 [DEBUG] conjure-up/canonical-kubernetes - gui.py:13 - Rendering bootstrap wait
2017-06-29 11:46:22,164 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting PreDeployComplete at conjureup/juju.py:517 in task _do_deploy at conjureup/controllers/deploy/gui.py:239
2017-06-29 11:46:22,301 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting PreDeployComplete at conjureup/juju.py:517 in task _do_deploy at conjureup/controllers/deploy/gui.py:239
2017-06-29 11:46:22,416 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting PreDeployComplete at conjureup/juju.py:517 in task _do_deploy at conjureup/controllers/deploy/gui.py:239
2017-06-29 11:46:22,530 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting PreDeployComplete at conjureup/juju.py:517 in task _do_deploy at conjureup/controllers/deploy/gui.py:239
2017-06-29 11:46:22,643 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting PreDeployComplete at conjureup/juju.py:517 in task _do_deploy at conjureup/controllers/deploy/gui.py:239
2017-06-29 11:46:22,761 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting PreDeployComplete at conjureup/juju.py:517 in task _do_deploy at conjureup/controllers/deploy/gui.py:239
2017-06-29 11:46:22,771 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting Bootstrapped at conjureup/controllers/bootstrapwait/gui.py:37
2017-06-29 11:46:22,773 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting RelationsAdded:flannel at /snap/conjure-up/527/usr/lib/python3.6/asyncio/events.py:127 in task wait at conjureup/events.py:95
2017-06-29 11:46:22,775 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting RelationsAdded:easyrsa at /snap/conjure-up/527/usr/lib/python3.6/asyncio/events.py:127 in task wait at conjureup/events.py:95
2017-06-29 11:46:22,777 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting RelationsAdded:etcd at /snap/conjure-up/527/usr/lib/python3.6/asyncio/events.py:127 in task wait at conjureup/events.py:95
2017-06-29 11:46:22,779 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting RelationsAdded:kubernetes-worker at /snap/conjure-up/527/usr/lib/python3.6/asyncio/events.py:127 in task wait at conjureup/events.py:95
2017-06-29 11:46:22,781 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting RelationsAdded:kubernetes-master at /snap/conjure-up/527/usr/lib/python3.6/asyncio/events.py:127 in task wait at conjureup/events.py:95
2017-06-29 11:46:22,783 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Awaiting RelationsAdded:kubeapi-load-balancer at /snap/conjure-up/527/usr/lib/python3.6/asyncio/events.py:127 in task wait at conjureup/events.py:95
2017-06-29 11:46:26,017 [DEBUG] conjure-up/canonical-kubernetes - juju.py:181 - proc done
2017-06-29 11:46:26,018 [ERROR] conjure-up/canonical-kubernetes - common.py:36 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-joyent-91a" on joyent/eu-ams-1', 'ERROR failed to bootstrap model: no image metadata found']
2017-06-29 11:46:26,020 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Setting Error at conjureup/events.py:147
2017-06-29 11:46:26,104 [ERROR] conjure-up/canonical-kubernetes - events.py:166 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/527/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 39, in do_bootstrap
    app.current_cloud_type))
Exception: Unable to bootstrap (cloud type: joyent)
2017-06-29 11:46:26,110 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:21 - Showing dialog for exception: Unable to bootstrap (cloud type: joyent)
2017-06-29 11:46:32,972 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Setting Shutdown at conjureup/events.py:143
2017-06-29 11:46:32,974 [DEBUG] conjure-up/canonical-kubernetes - events.py:55 - Received Shutdown at conjureup/events.py:180
2017-06-29 11:46:32,974 [INFO] conjure-up/canonical-kubernetes - events.py:184 - Shutting down
```

**Comment by tvansteenburgh** [comment]
@joedborg Okay, but that's on joyent, what about lxd?

**Comment by joedborg** [comment]
Sorry @tvansteenburgh, I got confused with another bug I raised earlier.  It does build with conjure-up now.  The only issue is this when I try and kill the controller:
```
ERROR getting controller environ: getting environ using bootstrap config from client store: validating cloud spec: non-empty endpoint "10.81.117.1:58313" not valid
```

**Comment by joedborg** [comment]
But this issue is resolved in conjure up

**Comment by shortwavedave** [comment]
Hello,
I'm having an issue that I think is related to this. The kubernetes spell doesn't seem to finish. Attached is my log dump. I initially had the storage pool as zfs, but changed it to dir after reading this thread. I still can't get it to finish. Any ideas?

<img width="1180" alt="conjure_error2" src="https://user-images.githubusercontent.com/22798574/49708837-8bbce200-fbee-11e8-9bdb-ba57f728c9d6.png">
[results-2018-12-09-20-03-34.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2661407/results-2018-12-09-20-03-34.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @shortwavedave 

I see you are deploying kubernetes on localhost on a system with nvidia hardware. And the nvidia-docker daemon fails to start. You should request for the docker runtime to be the one you get from the apt repository. 

Here is how to do that, in conjure-up on the "Configure Applications" screen, before you select "Deploy", select "Configure" the kubernetes-worker, then "Show Advance Configuration" and there for "docker_runtime" select "apt". 

As you can find be searching past issues, special hardware available through the lxc layer on localhost has always been giving us trouble. We are in the process of improving our docs and that will hopefully address this kind of annoyances https://github.com/juju-solutions/kubernetes-docs/issues/59 .

Thank you for using CDK

**Comment by syncharny** [comment]
@ktsakalozos Wow, that worked. Thank you so much!

**Comment by shortwavedave** [comment]
@ktsakalozos Wow, that worked. Thank you so much!

**Comment by blemelin** [comment]
I had the same problem. Setting "docker_runtime" to "apt" solved it as well. I might not be the only one, so should it be documented somewhere ?
